### ISSUE TITLE
Bug: Intersection time

### ISSUE THREAD

**Issue by nico-franco-gomez** [pyfar/pyrato#31] opened 2024-08-22 08:29 UTC
First of all, thank you for the nice functionality in this package!

I was looking at the implementation of the intersection time method and came across this line, which I believe is a bug, because the index should be outside the parenthesis: https://github.com/pyfar/pyrato/blob/8465c57ec1bd38b7b0a85d38f3a378d393e190f2/pyrato/edc.py#L975C27-L975C34

Additionally, I had troubles with an impulse response which had some delay (around 0,2 seconds prior to peak). This exception was raised `Regression failed: T would be Inf, setting to 0. Estimation terminated.` After getting rid of these samples, the method worked properly. I would suggest checking this kind of delays beforehand and cutting them automatically, so that it "just works".

**Comment by mberz** [comment] 2024-09-03 15:07
1. Thanks for reporting your issue. Could you specify more precisely where you would place the index? There are two parentheses closing on that line.
2. I think what you're suggesting is achieved by using the input argument `time_shift=False`. Since this behaviour does modify the impulse response input, it is off by default. Let me know if this solves your issue.

**Comment by mberz** [comment] 2024-09-03 15:40
@nico-franco-gomez: I've created a PR for the issue, would you mind checking if the changes agree with your suggestion?

**Comment by nico-franco-gomez** [comment] 2024-09-04 08:07
1. I believe the modification with the index is now right.
2. Since the time shift seems to be a necessary step for the correct computation, I would suggest to make it the default, but only applied to a copy of the IR (not on the original data). It would make the usage a bit easier, though in the end, it is of course subjective:)

**Comment by mberz** [comment] 2024-09-05 12:14
1. Thanks for checking.
2. The issue in this case would be that the returned intersection time and originally passed RIR would not match anymore. While this could of course be circumvented when the time shift is known, this would require adaption other functions. I'll consider this in the future, but for now only add a warning if the regression fails.

**Closed** 2024-09-07 10:09 UTC
